#!/bin/bash

set -e
while [ "$(basename "$(realpath .)")" != "pyreto" ]
do
    if [ $PWD == "/" ]
    then
        error "Not a pyreto project"
    fi
    cd ..
done

if [ -z "$1" ]
then
    echo "USAGE: $0 <name>"
    exit 1
fi
NAME="$1"

mkdir "$NAME"
echo "0.0.0" > "$NAME/VERSION.txt"
echo -e "# $NAME\n\n" > "$NAME/README.md"
touch "$NAME/requirements.txt"
